plugins {
    id 'java'
    id 'xyz.jpenilla.run-paper' version '3.0.2'
}

group = 'com.github.cinnaio'
version = '2.0.1-SNAPSHOT'

repositories {
    mavenCentral()
    maven {
        name = 'papermc'
        url = 'https://repo.papermc.io/repository/maven-public/'
    }
    maven {
        name = 'momirealms'
        url = 'https://repo.momirealms.net/releases/'
        metadataSources {
            mavenPom()
            artifact()
        }
    }
}

dependencies {
    compileOnly 'io.papermc.paper:paper-api:26.1.2.build.74-stable'
    compileOnly 'net.momirealms:craft-engine-core:26.8'
    compileOnly 'net.momirealms:craft-engine-bukkit:26.8'
}

java {
    toolchain.languageVersion = JavaLanguageVersion.of(25)
}

tasks {
    compileJava {
        options.encoding = 'UTF-8'
    }

    processResources {
        filteringCharset = 'UTF-8'
        filesMatching('paper-plugin.yml') {
            expand(version: project.version)
        }
    }

    runServer {
        minecraftVersion('26.1.2')
    }
}
