machines:
  tea-drying-pan:
    block-id: cgap:tea_drying_pan
    title: "<white><shift:-9><image:cgap:tea_drying_pan_gui><shift:-143>{progress}<shift:143><shift:-170><reset>炒茶（煮饭）锅"
    process-ticks: 100
    input-slot: 11
    output-slot: 15
    progress-image-prefix: cgap:tea_progress_
    progress-image-width: 108
    recipes:
      green-tea-clear:
        input:
          id: cgap:tea_leaf
          amount: 1
        conditions:
          weather: clear
        process-ticks: 100
        output:
          id: cgap:green_tea_leaf
          amount: 1
          material: DRIED_KELP
          name: "晴天绿茶干叶"
      green-tea-rain:
        input:
          id: cgap:tea_leaf
          amount: 1
        conditions:
          weather: rain
        process-ticks: 120
        output:
          id: cgap:green_tea_leaf
          amount: 1
          material: DRIED_KELP
          name: "雨天绿茶干叶"
      green-tea-thunder:
        input:
          id: cgap:tea_leaf
          amount: 1
        conditions:
          weather: thunder
        process-ticks: 140
        output:
          id: cgap:green_tea_leaf
          amount: 1
          material: DRIED_KELP
          name: "雷雨绿茶干叶"
